[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Favourites"
  pageRef = "favourites"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
