[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
