# Site settings
title: Nipun Agarwala
email: 
description: "Random thoughts."
# baseurl: ""
url: "http://nipunagarwala.github.io"
github_username:  nipunagarwala

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
    - jekyll-seo-tag
