# Site settings
title: Seshu Pavan
email: seshupavan05@gmail.com
description: "My Personal Blog"
# baseurl: ""
url: "https://seshupavan.github.io"
github_username:  seshupavan

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

